# Generated by Django 3.0.7 on 2020-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datePublished',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
